# Add $STORAGE_PATH to project before load.

include:
  - ../apps/jellyfin.compose.yml
  - ../apps/lidarr.compose.yml
  - ../apps/radarr.compose.yml
  - ../apps/sonarr.compose.yml

services:
  filebrowser:
    user: 1000:1000
    image: filebrowser/filebrowser:latest
    environment:
      - SERVICE_FQDN_FILEBROWSER_80
    volumes:
      - '/${project.STORAGE_PATH}/Media:/srv:rw'
      - media-filebrowser-db:/database
      - media-filebrowser-config:/config
    restart: unless-stopped
    
  # jellyfin:
  #   image: linuxserver/jellyfin:latest
  #   environment:
  #     - SERVICE_FQDN_JELLYFIN_8096
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Europe/London
  #     - JELLYFIN_PublishedServerUrl=$SERVICE_URL_JELLYFIN
  #   volumes:
  #     - jellyfin-config:/config
  #     - '/${project.STORAGE_PATH}/Media:/data:rw'
  #   restart: unless-stopped

  # sonarr:
  #   image: linuxserver/sonarr:latest
  #   environment:
  #     - SERVICE_FQDN_SONARR_8989
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Europe/London
  #   volumes:
  #     - media-sonarr-config:/config
  #     - '/${project.STORAGE_PATH}/Media/TV Shows:/tv:rw'
  #     - '/${project.STORAGE_PATH}/Downloads:/downloads:rw'
  #   restart: unless-stopped

  # radarr:
  #   image: lscr.io/linuxserver/radarr:latest
  #   environment:
  #     - SERVICE_FQDN_RADARR_7878
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Europe/London
  #   volumes:
  #     - media-radarr-config:/config
  #     - '/${project.STORAGE_PATH}/Media/Movies:/movies:rw'
  #     - '/${project.STORAGE_PATH}/Downloads:/downloads:rw'
  #   restart: unless-stopped

  # lidarr:
  #   image: 'lscr.io/linuxserver/lidarr:latest'
  #   environment:
  #     - SERVICE_FQDN_LIDARR_8686
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Europe/London
  #   volumes:
  #     - media-lidarr-config:/config:rw
  #     - '/${project.STORAGE_PATH}/Media/Music:/music:rw'
  #     - '/${project.STORAGE_PATH}/Downloads:/downloads:rw'
  #   restart: unless-stopped

volumes:
  media-jellyfin-config: null
  media-filebrowser-db: null
  media-filebrowser-config: null
  media-sonarr-config: null
  media-radarr-config: null
  media-lidarr-config: null