services:
  jellyfin:
    image: linuxserver/jellyfin:latest
    environment:
      - SERVICE_FQDN_JELLYFIN_8096
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - JELLYFIN_PublishedServerUrl=$SERVICE_URL_JELLYFIN
    volumes:
      - jellyfin-config:/config
      - '/Data/Media:/data:rw'