services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    environment:
      - SERVICE_FQDN_RADARR_7878
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - radarr-config:/config
      - '/Data/Media/Movies:/movies:rw'
      - '/Data/Downloads:/downloads:rw'
    restart: unless-stopped