services:
  sonarr:
    image: linuxserver/sonarr:latest
    environment:
      - SERVICE_FQDN_SONARR_8989
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - sonarr-config:/config
      - '/Data/Media/TV Shows:/tv:rw'
      - '/Data/Downloads:/downloads:rw'
    restart: unless-stopped