services:
  garrysmod-server:
    image: ceifa/garrysmod:latest
    environment:
      - ARGS="+host_workshop_collection ${WORKSHOP_COLLECTION_ID}"
      - HOSTNAME="${SERVER_NAME:?my-server}"
      - MAXPLAYERS="24"
      - GAMEMODE=${SERVER_GAMEMODE:?sandbox}
      - MAP=${SERVER_MAP:?gm_construct}
      - GSLT=${GSLT}
    ports:
      - 27015:27015/udp
      - 27015:27015
      - 27005:27005/udp
    volumes:
      - "/Data/GameServers/Shared/garrysmod/mounts:/home/gmod/mounts:rw"
      - "/Data/GameServers/Shared/garrysmod/addons:/home/gmod/server/garrysmod/addons:rw"
      - "/Data/GameServers/Shared/garrysmod/gamemodes:/home/gmod/server/garrysmod/gamemodes:rw"
      - gmod-server-data:/home/gmod/server/garrysmod/data:rw
    restart: unless-stopped

volumes:
  gmod-server-data: null